use_frameworks!

target 'macOS_Tests' do
  platform :macos, '10.15'
  pod 'RepeatableRandom', :path => '../'
end

target 'iOS_Tests' do
  platform :ios, '12.0'
  pod 'RepeatableRandom', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Fix Xcode warning update to recommended settings caused by overriding architecture settings
    # https://github.com/CocoaPods/CocoaPods/issues/8242#issuecomment-572046678
    target.build_configurations.each do |config|
      config.build_settings.delete('ARCHS')
    end
  end
end
