name: Example Tests

on:
  push:
    branches:
      - main
      - '!experiment/**'
      - experiment/example-tests/**
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, iOS]
    steps:
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v2
    - name: destination
      id: destination
      run: |
        if [ $OS == 'iOS' ]
        then
            echo "::set-output name=destination::\"platform=iOS Simulator,name=iPhone 8\""
        else
            echo "::set-output name=destination::platform=macOS"
        fi
      env:
        OS: ${{ matrix.os }}
    - name: ${{ matrix.os }} Tests
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        workspace: Example/RepeatableRandom.xcworkspace
        scheme: Tests
        destination: ${{ steps.destination.outputs.destination }}
        result-bundle-path: test-results/${{ matrix.os }}
        build-settings: -test-timeouts-enabled YES
    - name: Save crash reports
      if: failure()
      run: find ~/Library/Logs/DiagnosticReports/*.crash
        -exec cp {} ./test-results \; || true
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -FSry results.zip test-results || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results-${{ matrix.os }}
        path: results.zip
