name: Example Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        scheme: [macOS_Tests, iOS_Tests]
    steps:
    - uses: actions/checkout@v2
    - name: macOS Tests
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        workspace: Example/RepeatableRandom.xcworkspace
        scheme: ${{ matrix.scheme }}
        result-bundle-path: test-results/${{ matrix.scheme }}
        build-settings: -test-timeouts-enabled YES
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -FSry results.zip test-results || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: results.zip
